# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainCrackWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        Dialog.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.frame.setStyleSheet("#frame\n"
"{\n"
"    image: url(:/q/nvwrign.jpg);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.passwordEdit = QtWidgets.QTextEdit(self.frame)
        self.passwordEdit.setGeometry(QtCore.QRect(180, 180, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setObjectName("passwordEdit")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(180, 250, 441, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.selectFileBtn = QtWidgets.QToolButton(self.frame)
        self.selectFileBtn.setGeometry(QtCore.QRect(640, 250, 51, 31))
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(70, 50, 661, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(90, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_4.setObjectName("label_4")
        self.operateBtn_2 = QtWidgets.QPushButton(self.frame)
        self.operateBtn_2.setGeometry(QtCore.QRect(500, 470, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.operateBtn_2.setFont(font)
        self.operateBtn_2.setObjectName("operateBtn_2")
        self.exitBtn_2 = QtWidgets.QPushButton(self.frame)
        self.exitBtn_2.setGeometry(QtCore.QRect(630, 470, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitBtn_2.setFont(font)
        self.exitBtn_2.setObjectName("exitBtn_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selectFileBtn.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "选择文件"))
        self.label_5.setText(_translate("Dialog", "本功能可用于去除没有打开口令的PDF文件的部分操作限制，如禁止复制、\n"
"禁止打印等。对于有打开口令的文件，需要输入打开口令才能去除。\n"
"去除加密后的文件在原文件夹下保存为原文件名，原文件名字前会加上raw."))
        self.label_4.setText(_translate("Dialog", "打开口令"))
        self.operateBtn_2.setText(_translate("Dialog", "去除加密"))
        self.exitBtn_2.setText(_translate("Dialog", "退出"))
import pictures_rc
