# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 521)
        self.operateBtn = QtWidgets.QPushButton(Dialog)
        self.operateBtn.setGeometry(QtCore.QRect(520, 440, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.operateBtn.setFont(font)
        self.operateBtn.setObjectName("operateBtn")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(170, 30, 611, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.selectFileBtn = QtWidgets.QToolButton(Dialog)
        self.selectFileBtn.setGeometry(QtCore.QRect(580, 120, 51, 31))
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 310, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(120, 120, 441, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 310, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.selectFileBtn_2 = QtWidgets.QToolButton(Dialog)
        self.selectFileBtn_2.setGeometry(QtCore.QRect(580, 310, 51, 31))
        self.selectFileBtn_2.setObjectName("selectFileBtn_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.operateBtn.setText(_translate("Dialog", "转换"))
        self.label_5.setText(_translate("Dialog", "将ppt文件转化为pdf文件。"))
        self.selectFileBtn.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "选择文件"))
        self.label_3.setText(_translate("Dialog", "保存路径"))
        self.selectFileBtn_2.setText(_translate("Dialog", "..."))
