# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(985, 725)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 750))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, -10, 1001, 741))
        self.graphicsView.setStyleSheet("background-image: url(:/q/sdvc.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 985, 26))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_R = QtWidgets.QMenu(self.menubar)
        self.menu_R.setObjectName("menu_R")
        self.menu_T = QtWidgets.QMenu(self.menubar)
        self.menu_T.setObjectName("menu_T")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.actionPPT_PDF = QtWidgets.QAction(MainWindow)
        self.actionPPT_PDF.setObjectName("actionPPT_PDF")
        self.actionWord_PDF = QtWidgets.QAction(MainWindow)
        self.actionWord_PDF.setObjectName("actionWord_PDF")
        self.menu_F.addAction(self.action)
        self.menu_F.addAction(self.action_2)
        self.menu_R.addAction(self.action_3)
        self.menu_R.addAction(self.action_4)
        self.menu_R.addAction(self.action_5)
        self.menu_R.addAction(self.action_6)
        self.menu_T.addAction(self.actionPPT_PDF)
        self.menu_T.addAction(self.actionWord_PDF)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_R.menuAction())
        self.menubar.addAction(self.menu_T.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_F.setTitle(_translate("MainWindow", "提取(&F)"))
        self.menu_R.setTitle(_translate("MainWindow", "编辑(R)"))
        self.menu_T.setTitle(_translate("MainWindow", "转换(T)"))
        self.action.setText(_translate("MainWindow", "文字(L)"))
        self.action_2.setText(_translate("MainWindow", "表格(K)"))
        self.action_3.setText(_translate("MainWindow", "去除加密"))
        self.action_4.setText(_translate("MainWindow", "拆分"))
        self.action_5.setText(_translate("MainWindow", "合并"))
        self.action_6.setText(_translate("MainWindow", "删除页面"))
        self.actionPPT_PDF.setText(_translate("MainWindow", "PPT转PDF"))
        self.actionWord_PDF.setText(_translate("MainWindow", "Word转PDF"))

import pictures_rc