# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppt2pdfWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(851, 737)
        Dialog.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setPointSize(13)
        Dialog.setFont(font)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(190, 430, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(190, 230, 471, 161))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.selectFileBtn = QtWidgets.QToolButton(Dialog)
        self.selectFileBtn.setGeometry(QtCore.QRect(690, 230, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.selectFileBtn.setFont(font)
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 430, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.selectPathBtn = QtWidgets.QToolButton(Dialog)
        self.selectPathBtn.setGeometry(QtCore.QRect(690, 430, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.selectPathBtn.setFont(font)
        self.selectPathBtn.setObjectName("selectPathBtn")
        self.exitBtn = QtWidgets.QPushButton(Dialog)
        self.exitBtn.setGeometry(QtCore.QRect(640, 580, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.operateBtn = QtWidgets.QPushButton(Dialog)
        self.operateBtn.setGeometry(QtCore.QRect(510, 580, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.operateBtn.setFont(font)
        self.operateBtn.setObjectName("operateBtn")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(80, 70, 671, 111))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "选择文件"))
        self.selectFileBtn.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "保存路径"))
        self.selectPathBtn.setText(_translate("Dialog", "..."))
        self.exitBtn.setText(_translate("Dialog", "取消"))
        self.operateBtn.setText(_translate("Dialog", "转换"))
        self.label_5.setText(_translate("Dialog", "将ppt文件批量转换为pdf文件。\n"
"1. 生成的pdf文件名与原ppt文件相同。\n"
"2. 保存路径不选默认为原路径（要求所选的所有ppt路径相同）。"))
import pictures_rc
