# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crackDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 588)
        self.selectFileBtn = QtWidgets.QToolButton(Dialog)
        self.selectFileBtn.setGeometry(QtCore.QRect(580, 220, 51, 31))
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 220, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exitBtn = QtWidgets.QPushButton(Dialog)
        self.exitBtn.setGeometry(QtCore.QRect(500, 520, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(120, 220, 441, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.operateBtn = QtWidgets.QPushButton(Dialog)
        self.operateBtn.setGeometry(QtCore.QRect(380, 520, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.operateBtn.setFont(font)
        self.operateBtn.setObjectName("operateBtn")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 410, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.selectPathBtn = QtWidgets.QToolButton(Dialog)
        self.selectPathBtn.setGeometry(QtCore.QRect(580, 410, 51, 31))
        self.selectPathBtn.setObjectName("selectPathBtn")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 410, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 611, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.passwordEdit = QtWidgets.QTextEdit(Dialog)
        self.passwordEdit.setGeometry(QtCore.QRect(120, 150, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setObjectName("passwordEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selectFileBtn.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "选择文件"))
        self.exitBtn.setText(_translate("Dialog", "取消"))
        self.operateBtn.setText(_translate("Dialog", "去除加密"))
        self.selectPathBtn.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "保存路径"))
        self.label_5.setText(_translate("Dialog", "本功能可用于去除没有打开口令的PDF文件的部分操作限制，如禁止复制、\n"
"禁止打印等。对于有打开口令的文件，需要输入打开口令才能去除。"))
        self.label_4.setText(_translate("Dialog", "打开口令"))
