# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 588)
        self.selectFileBtn = QtWidgets.QToolButton(Dialog)
        self.selectFileBtn.setGeometry(QtCore.QRect(580, 70, 51, 31))
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exitBtn = QtWidgets.QPushButton(Dialog)
        self.exitBtn.setGeometry(QtCore.QRect(490, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(120, 70, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.operateBtn = QtWidgets.QPushButton(Dialog)
        self.operateBtn.setGeometry(QtCore.QRect(370, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.operateBtn.setFont(font)
        self.operateBtn.setObjectName("operateBtn")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 140, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.selectPathBtn = QtWidgets.QToolButton(Dialog)
        self.selectPathBtn.setGeometry(QtCore.QRect(580, 140, 51, 31))
        self.selectPathBtn.setObjectName("selectPathBtn")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(120, 210, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 290, 611, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selectFileBtn.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "选择文件"))
        self.exitBtn.setText(_translate("Dialog", "取消"))
        self.operateBtn.setText(_translate("Dialog", "删除"))
        self.selectPathBtn.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "保存路径"))
        self.label_4.setText(_translate("Dialog", "页面选择"))
        self.label_5.setText(_translate("Dialog", "页面选择说明：输入格式为\"begin-end\"，前者表示起始页面页码数，后者\n"
"表示末页面页码数。页码从1开始计数，包含最后一页。eg.\"1-3\"表示删除\n"
"第1、2、3页。对于某些目录部分页码用罗马数字表示的文档，其页码仍然\n"
"用实际数字表示。（实际数字可以在adobe reader上的括号里查看）"))
