# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileSelectDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(670, 588)
        self.selectFileBtn = QtWidgets.QToolButton(Dialog)
        self.selectFileBtn.setGeometry(QtCore.QRect(570, 170, 51, 31))
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exitBtn = QtWidgets.QPushButton(Dialog)
        self.exitBtn.setGeometry(QtCore.QRect(490, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(110, 170, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.operateBtn = QtWidgets.QPushButton(Dialog)
        self.operateBtn.setGeometry(QtCore.QRect(370, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.operateBtn.setFont(font)
        self.operateBtn.setObjectName("operateBtn")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 541, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(110, 240, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.selectPathBtn = QtWidgets.QToolButton(Dialog)
        self.selectPathBtn.setGeometry(QtCore.QRect(570, 240, 51, 31))
        self.selectPathBtn.setObjectName("selectPathBtn")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selectFileBtn.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "选择文件"))
        self.exitBtn.setText(_translate("Dialog", "取消"))
        self.operateBtn.setText(_translate("Dialog", "去除加密"))
        self.label_2.setText(_translate("Dialog", "说明：本功能可去除没有打开口令的pdf文件的保护，如限制修改、\n"
"限制复制、限制打印等。"))
        self.selectPathBtn.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "保存路径"))
