# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mergeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(864, 719)
        self.exitBtn = QtWidgets.QPushButton(Dialog)
        self.exitBtn.setGeometry(QtCore.QRect(650, 590, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.operateBtn = QtWidgets.QPushButton(Dialog)
        self.operateBtn.setGeometry(QtCore.QRect(510, 590, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.operateBtn.setFont(font)
        self.operateBtn.setObjectName("operateBtn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.selectPathBtn = QtWidgets.QToolButton(Dialog)
        self.selectPathBtn.setGeometry(QtCore.QRect(650, 430, 51, 31))
        self.selectPathBtn.setObjectName("selectPathBtn")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 430, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.selectFileBtn = QtWidgets.QToolButton(Dialog)
        self.selectFileBtn.setGeometry(QtCore.QRect(650, 190, 51, 31))
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(190, 190, 441, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(190, 430, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 40, 641, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exitBtn.setText(_translate("Dialog", "取消"))
        self.operateBtn.setText(_translate("Dialog", "确认"))
        self.label.setText(_translate("Dialog", "选择文件"))
        self.selectPathBtn.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "保存路径"))
        self.selectFileBtn.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "选择两个pdf文件后将其按先后顺序合并，目前仅支持两个文件。"))
