# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try0401.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(645, 542)
        font = QtGui.QFont()
        font.setPointSize(9)
        Home.setFont(font)
        self.crackerBtn = QtWidgets.QPushButton(Home)
        self.crackerBtn.setGeometry(QtCore.QRect(50, 440, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crackerBtn.setFont(font)
        self.crackerBtn.setObjectName("cracker")
        self.batchCracker = QtWidgets.QPushButton(Home)
        self.batchCracker.setGeometry(QtCore.QRect(190, 440, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.batchCracker.setFont(font)
        self.batchCracker.setObjectName("batchCracker")
        self.pageDeleter = QtWidgets.QPushButton(Home)
        self.pageDeleter.setGeometry(QtCore.QRect(50, 360, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pageDeleter.setFont(font)
        self.pageDeleter.setObjectName("pageDeleter")
        self.mergeBtn = QtWidgets.QPushButton(Home)
        self.mergeBtn.setGeometry(QtCore.QRect(190, 360, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mergeBtn.setFont(font)
        self.mergeBtn.setObjectName("mergeBtn")
        self.exitBtn = QtWidgets.QPushButton(Home)
        self.exitBtn.setGeometry(QtCore.QRect(500, 440, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Home"))
        self.crackerBtn.setText(_translate("Home", "去除加密"))
        self.batchCracker.setText(_translate("Home", "批量去除加密"))
        self.pageDeleter.setText(_translate("Home", "删除页面"))
        self.mergeBtn.setText(_translate("Home", "合并pdf"))
        self.exitBtn.setText(_translate("Home", "退出"))
